site_name: Fuseline
site_description: Workflow runner for Python workloads.
site_author: Sam Hart
repo_url: https://github.com/jsam/fuseline

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys; sys.path.append("..")

theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
