services:
  db:
    # Postgres image with the pgvector extension built in
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: fuseline
      POSTGRES_PASSWORD: fuseline
      POSTGRES_DB: fuseline
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fuseline"]
      interval: 5s
      timeout: 5s
      retries: 5
  broker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.broker
    environment:
      DATABASE_URL: postgresql://fuseline:fuseline@db:5432/fuseline
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 5s
      retries: 20
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    environment:
      BROKER_URL: http://broker:8000
    depends_on:
      broker:
        condition: service_healthy
