version: '3'
services:
  db:
    image: pgvector/pgvector:latest
    environment:
      POSTGRES_USER: fuseline
      POSTGRES_PASSWORD: fuseline
      POSTGRES_DB: fuseline
    ports:
      - "5432:5432"
  broker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.broker
    environment:
      DATABASE_URL: postgresql://fuseline:fuseline@db:5432/fuseline
    depends_on:
      - db
    ports:
      - "8000:8000"
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    environment:
      BROKER_URL: http://broker:8000
    depends_on:
      - broker
