project:
  type: website
  output-dir: _site

website:
  title: "Fuseline"
  repo-url: https://github.com/jsam/fuseline
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: usage.qmd
        text: Usage Guide
      - href: api.qmd
        text: API Reference

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
